# Generated by Django 3.2 on 2021-04-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(default=None, max_length=100, verbose_name='Disk Memory')),
                ('loading', models.CharField(default=None, max_length=100, verbose_name='Disk Loading')),
            ],
        ),
        migrations.CreateModel(
            name='OSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='OS Name')),
                ('version', models.CharField(default=None, max_length=100, verbose_name='OS Version')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Processor Name')),
                ('architecture', models.CharField(default=None, max_length=100, verbose_name='Processor Architecture')),
                ('temperature', models.CharField(default=None, max_length=100, verbose_name='Processor Temperature')),
                ('loading', models.CharField(default=None, max_length=100, verbose_name='Processor Loading')),
            ],
        ),
        migrations.CreateModel(
            name='SocketConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default=None, max_length=100, verbose_name='Socket Info Host')),
                ('ip_address', models.CharField(default=None, max_length=100, verbose_name='Socket Info IP Address')),
                ('mac_address', models.CharField(default=None, max_length=100, verbose_name='Socket Info MAC Address')),
            ],
        ),
        migrations.CreateModel(
            name='PCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('ram', models.CharField(default=None, max_length=20, verbose_name='RAM')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_configuration.diskconfiguration')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_configuration.osconfiguration')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_configuration.processorconfiguration')),
                ('socket_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_configuration.socketconfiguration')),
            ],
        ),
    ]
