# Generated by Django 3.2 on 2021-04-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('os_name', models.CharField(max_length=100, verbose_name='OS Name')),
                ('os_version', models.CharField(max_length=100, verbose_name='OS Version')),
                ('processor_name', models.CharField(max_length=100, verbose_name='Processor Name')),
                ('processor_architecture', models.CharField(max_length=100, verbose_name='Processor Architecture')),
                ('processor_temperature', models.CharField(max_length=100, verbose_name='Processor Temperature')),
                ('processor_loading', models.CharField(max_length=100, verbose_name='Processor Loading')),
                ('socket_info_host', models.CharField(max_length=100, verbose_name='Socket Info Host')),
                ('socket_info_ip_address', models.CharField(max_length=100, verbose_name='Socket Info IP Address')),
                ('socket_info_mac_address', models.CharField(max_length=100, verbose_name='Socket Info MAC Address')),
                ('disk_memory', models.CharField(max_length=100, verbose_name='Disk Memory')),
                ('disk_loading', models.CharField(max_length=100, verbose_name='Disk Loading')),
                ('ram', models.CharField(max_length=20, verbose_name='RAM')),
            ],
        ),
    ]
