# Generated by Django 3.2 on 2021-05-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_system_type', models.CharField(default=None, max_length=100, verbose_name='File System Type')),
                ('total_memory', models.CharField(default=None, max_length=100, verbose_name='Total Disk Memory')),
                ('available', models.CharField(default=None, max_length=100, verbose_name='Available Disk Memory')),
                ('used', models.CharField(default=None, max_length=100, verbose_name='Used Disk Memory')),
                ('used_in_persents', models.CharField(default=None, max_length=100, verbose_name='Used Disk Memory In Persents')),
            ],
        ),
        migrations.CreateModel(
            name='PCConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_configuration.diskconfigurationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Processor Name')),
                ('architecture', models.CharField(default=None, max_length=100, verbose_name='Processor Architecture')),
                ('total_cores', models.IntegerField(default=None, verbose_name='Total Cores')),
                ('max_frequency', models.CharField(default=None, max_length=100, verbose_name='Max Frequency')),
                ('current_frequency', models.CharField(default=None, max_length=100, verbose_name='Current Frequency')),
                ('temperature', models.CharField(default=None, max_length=100, verbose_name='Processor Temperature')),
                ('loading', models.CharField(default=None, max_length=100, verbose_name='Processor Loading')),
                ('usage_per_core', models.CharField(default=None, max_length=1000, verbose_name='Usage Per Core')),
            ],
        ),
        migrations.CreateModel(
            name='RAMConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_memory', models.CharField(default=None, max_length=100, verbose_name='Total RAM Memory')),
                ('available', models.CharField(default=None, max_length=100, verbose_name='Available RAM Memory')),
                ('used', models.CharField(default=None, max_length=100, verbose_name='Used RAM Memory')),
                ('used_in_percents', models.CharField(default=None, max_length=100, verbose_name='Used RAM Memory In Percents')),
            ],
        ),
        migrations.RemoveField(
            model_name='pcconfiguration',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='pcconfiguration',
            name='os',
        ),
        migrations.RemoveField(
            model_name='pcconfiguration',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='pcconfiguration',
            name='socket_info',
        ),
        migrations.RenameModel(
            old_name='OSConfiguration',
            new_name='OSConfigurationModel',
        ),
        migrations.RenameModel(
            old_name='SocketConfiguration',
            new_name='SocketConfigurationModel',
        ),
        migrations.DeleteModel(
            name='DiskConfiguration',
        ),
        migrations.DeleteModel(
            name='PCConfiguration',
        ),
        migrations.DeleteModel(
            name='ProcessorConfiguration',
        ),
        migrations.AddField(
            model_name='pcconfigurationmodel',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_configuration.osconfigurationmodel'),
        ),
        migrations.AddField(
            model_name='pcconfigurationmodel',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_configuration.processorconfigurationmodel'),
        ),
        migrations.AddField(
            model_name='pcconfigurationmodel',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_configuration.ramconfigurationmodel'),
        ),
        migrations.AddField(
            model_name='pcconfigurationmodel',
            name='socket_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_configuration.socketconfigurationmodel'),
        ),
    ]
