# Generated by Django 3.2 on 2021-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configuration', '0002_auto_20210522_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diskconfigurationmodel',
            name='used_in_persents',
        ),
        migrations.AddField(
            model_name='diskconfigurationmodel',
            name='used_in_percents',
            field=models.CharField(default=None, max_length=100, verbose_name='Used Disk Memory In Percents'),
        ),
    ]
