# Generated by Django 3.2 on 2021-06-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configuration', '0003_auto_20210522_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='GPU Name')),
                ('temperature', models.CharField(default=None, max_length=100, verbose_name='GPU Temperature')),
                ('loading', models.CharField(default=None, max_length=100, verbose_name='GPU Loading')),
                ('total_memory', models.CharField(default=None, max_length=100, verbose_name='Total GPU Memory')),
                ('available', models.CharField(default=None, max_length=100, verbose_name='Available GPU Memory')),
                ('used', models.CharField(default=None, max_length=100, verbose_name='Used GPU Memory')),
                ('used_in_percents', models.CharField(default=None, max_length=100, verbose_name='Used GPU Memory In Percents')),
            ],
        ),
        migrations.AddField(
            model_name='pcconfigurationmodel',
            name='gpu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pc_configuration.gpuconfigurationmodel'),
        ),
    ]
