# Generated by Django 3.2 on 2021-06-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configuration', '0004_auto_20210612_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcconfigurationmodel',
            name='gpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_configuration.gpuconfigurationmodel'),
        ),
    ]
